// Code generated by internal/cmd/genevents; DO NOT EDIT.

package credbound

import "context"

type UnimplementedTransactionHook struct{}

var _ TransactionHook = UnimplementedTransactionHook{}

func (UnimplementedTransactionHook) unimplementedTransactionHook() {}

func (UnimplementedTransactionHook) ApplyUserCreate(context.Context, Tx, UserCreateChange) error {
	return nil
}

func (UnimplementedTransactionHook) ApplyWorkspaceCreate(context.Context, Tx, WorkspaceCreateChange) error {
	return nil
}

func (UnimplementedTransactionHook) ApplyUserStatusChange(context.Context, Tx, UserStatusChange) error {
	return nil
}

func (UnimplementedTransactionHook) ApplyUserProfileChange(context.Context, Tx, UserProfileChange) error {
	return nil
}

func (UnimplementedTransactionHook) ApplyWorkspaceChange(context.Context, Tx, WorkspaceChange) error {
	return nil
}

func (UnimplementedTransactionHook) ApplyMembershipChange(context.Context, Tx, MembershipChange) error {
	return nil
}

func (UnimplementedTransactionHook) ApplyWorkspaceInvitationChange(context.Context, Tx, WorkspaceInvitationChange) error {
	return nil
}

func (UnimplementedTransactionHook) ApplyWorkspaceDomainChange(context.Context, Tx, WorkspaceDomainChange) error {
	return nil
}

func (UnimplementedTransactionHook) ApplyPasswordChange(context.Context, Tx, PasswordChange) error {
	return nil
}

func (UnimplementedTransactionHook) ApplyEmailAddition(context.Context, Tx, EmailAddition) error {
	return nil
}

func (UnimplementedTransactionHook) ApplyEmailConfirmation(context.Context, Tx, EmailConfirmation) error {
	return nil
}

func (UnimplementedTransactionHook) ApplyPrimaryEmailChange(context.Context, Tx, PrimaryEmailChange) error {
	return nil
}

func (UnimplementedTransactionHook) ApplyEmailRemoval(context.Context, Tx, EmailRemoval) error {
	return nil
}

func (UnimplementedTransactionHook) ApplyTOTPEnrollment(context.Context, Tx, TOTPEnrollmentChange) error {
	return nil
}

func (UnimplementedTransactionHook) ApplyTOTPActivation(context.Context, Tx, TOTPActivation) error {
	return nil
}

func (UnimplementedTransactionHook) ApplyTOTPDisable(context.Context, Tx, TOTPDisable) error {
	return nil
}

func (UnimplementedTransactionHook) ApplyPasskeyRegistration(context.Context, Tx, PasskeyRegistration) error {
	return nil
}

func (UnimplementedTransactionHook) ApplyPasskeyDeletion(context.Context, Tx, PasskeyDeletion) error {
	return nil
}

func (UnimplementedTransactionHook) ApplyPATCreation(context.Context, Tx, PATCreation) error {
	return nil
}

func (UnimplementedTransactionHook) ApplyPATRevocation(context.Context, Tx, PATRevocation) error {
	return nil
}

func (UnimplementedTransactionHook) ApplyUserCredentialRevocation(context.Context, Tx, UserCredentialRevocation) error {
	return nil
}

func (UnimplementedTransactionHook) ApplySecondFactorReset(context.Context, Tx, SecondFactorReset) error {
	return nil
}

func (UnimplementedTransactionHook) ApplyUserAnonymization(context.Context, Tx, UserAnonymization) error {
	return nil
}

func (UnimplementedTransactionHook) ApplyRecoveryCodeRegeneration(context.Context, Tx, RecoveryCodeRegeneration) error {
	return nil
}

func (UnimplementedTransactionHook) ApplySessionCreation(context.Context, Tx, SessionCreation) error {
	return nil
}

func (UnimplementedTransactionHook) ApplySessionRevocation(context.Context, Tx, SessionRevocation) error {
	return nil
}

func (UnimplementedTransactionHook) ApplyUserSessionRevocation(context.Context, Tx, UserSessionRevocation) error {
	return nil
}

func (UnimplementedTransactionHook) ApplySSOLink(context.Context, Tx, SSOLink) error { return nil }

func (UnimplementedTransactionHook) ApplySSOUnlink(context.Context, Tx, SSOUnlink) error { return nil }

func (UnimplementedTransactionHook) ApplyRoleGrant(context.Context, Tx, RoleGrant) error { return nil }

func (UnimplementedTransactionHook) ApplyInstanceRoleChange(context.Context, Tx, InstanceRoleChange) error {
	return nil
}

func (UnimplementedTransactionHook) ApplyInstanceRoleRemoval(context.Context, Tx, InstanceRoleRemoval) error {
	return nil
}

func (UnimplementedTransactionHook) ApplyClientAudit(context.Context, Tx, ClientAuditRecord) error {
	return nil
}

func (UnimplementedTransactionHook) ApplySCIMConfigurationCreate(context.Context, Tx, SCIMConfigurationChange) error {
	return nil
}

func (UnimplementedTransactionHook) ApplySCIMUserProvision(context.Context, Tx, SCIMUserChange) error {
	return nil
}

func (UnimplementedTransactionHook) ApplySCIMUserUpdate(context.Context, Tx, SCIMUserChange) error {
	return nil
}

func (UnimplementedTransactionHook) ApplySCIMUserDeprovision(context.Context, Tx, SCIMUserChange) error {
	return nil
}

func (UnimplementedTransactionHook) ApplySCIMGroupUpsert(context.Context, Tx, SCIMGroupChange) error {
	return nil
}

func (UnimplementedTransactionHook) ApplySCIMGroupDelete(context.Context, Tx, SCIMGroupChange) error {
	return nil
}

func (UnimplementedTransactionHook) ApplyOAuthChange(context.Context, Tx, OAuthChange) error {
	return nil
}

type UnimplementedEventListener struct{}

var _ EventListener = UnimplementedEventListener{}

func (UnimplementedEventListener) unimplementedEventListener() {}

func (UnimplementedEventListener) OnBootstrapCompleted(context.Context, BootstrapCompletedEvent) error {
	return nil
}

func (UnimplementedEventListener) OnSignUpCompleted(context.Context, SignUpCompletedEvent) error {
	return nil
}

func (UnimplementedEventListener) OnUserCreated(context.Context, UserCreatedEvent) error { return nil }

func (UnimplementedEventListener) OnWorkspaceCreated(context.Context, WorkspaceCreatedEvent) error {
	return nil
}

func (UnimplementedEventListener) OnUserStatusChanged(context.Context, UserStatusEvent) error {
	return nil
}

func (UnimplementedEventListener) OnUserProfileUpdated(context.Context, UserProfileUpdatedEvent) error {
	return nil
}

func (UnimplementedEventListener) OnWorkspaceChanged(context.Context, WorkspaceChangedEvent) error {
	return nil
}

func (UnimplementedEventListener) OnMembershipChanged(context.Context, MembershipChangedEvent) error {
	return nil
}

func (UnimplementedEventListener) OnWorkspaceInvitationCreated(context.Context, WorkspaceInvitationEvent) error {
	return nil
}

func (UnimplementedEventListener) OnWorkspaceInvitationAccepted(context.Context, WorkspaceInvitationEvent) error {
	return nil
}

func (UnimplementedEventListener) OnWorkspaceInvitationRevoked(context.Context, WorkspaceInvitationEvent) error {
	return nil
}

func (UnimplementedEventListener) OnWorkspaceDomainCreated(context.Context, WorkspaceDomainEvent) error {
	return nil
}

func (UnimplementedEventListener) OnWorkspaceDomainConfirmed(context.Context, WorkspaceDomainEvent) error {
	return nil
}

func (UnimplementedEventListener) OnWorkspaceDomainPolicyUpdated(context.Context, WorkspaceDomainEvent) error {
	return nil
}

func (UnimplementedEventListener) OnWorkspaceDomainRemoved(context.Context, WorkspaceDomainEvent) error {
	return nil
}

func (UnimplementedEventListener) OnPasswordChanged(context.Context, PasswordChangedEvent) error {
	return nil
}

func (UnimplementedEventListener) OnPasswordRehashed(context.Context, PasswordRehashedEvent) error {
	return nil
}

func (UnimplementedEventListener) OnAuthenticationSucceeded(context.Context, AuthenticationEvent) error {
	return nil
}

func (UnimplementedEventListener) OnAuthenticationFailed(context.Context, AuthenticationFailureEvent) error {
	return nil
}

func (UnimplementedEventListener) OnStepUpDenied(context.Context, StepUpDeniedEvent) error {
	return nil
}

func (UnimplementedEventListener) OnAuthorizationDenied(context.Context, AuthorizationDeniedEvent) error {
	return nil
}

func (UnimplementedEventListener) OnEmailAdded(context.Context, EmailAddedEvent) error { return nil }

func (UnimplementedEventListener) OnEmailConfirmed(context.Context, EmailConfirmedEvent) error {
	return nil
}

func (UnimplementedEventListener) OnPrimaryEmailChanged(context.Context, PrimaryEmailChangedEvent) error {
	return nil
}

func (UnimplementedEventListener) OnEmailRemoved(context.Context, EmailRemovedEvent) error {
	return nil
}

func (UnimplementedEventListener) OnTOTPEnrollmentStarted(context.Context, TOTPEnrollmentStartedEvent) error {
	return nil
}

func (UnimplementedEventListener) OnTOTPActivated(context.Context, TOTPActivatedEvent) error {
	return nil
}

func (UnimplementedEventListener) OnTOTPDisabled(context.Context, TOTPDisabledEvent) error {
	return nil
}

func (UnimplementedEventListener) OnTOTPVerified(context.Context, TOTPVerifiedEvent) error {
	return nil
}

func (UnimplementedEventListener) OnTOTPReplayRejected(context.Context, TOTPReplayRejectedEvent) error {
	return nil
}

func (UnimplementedEventListener) OnRecoveryCodeConsumed(context.Context, RecoveryCodeConsumedEvent) error {
	return nil
}

func (UnimplementedEventListener) OnPasskeyRegistered(context.Context, PasskeyRegisteredEvent) error {
	return nil
}

func (UnimplementedEventListener) OnPasskeyDeleted(context.Context, PasskeyDeletedEvent) error {
	return nil
}

func (UnimplementedEventListener) OnPasskeyAuthenticated(context.Context, PasskeyAuthenticatedEvent) error {
	return nil
}

func (UnimplementedEventListener) OnPATCreated(context.Context, PATCreatedEvent) error { return nil }

func (UnimplementedEventListener) OnPATRevoked(context.Context, PATRevokedEvent) error { return nil }

func (UnimplementedEventListener) OnUserCredentialsRevoked(context.Context, UserCredentialsRevokedEvent) error {
	return nil
}

func (UnimplementedEventListener) OnSecondFactorReset(context.Context, SecondFactorResetEvent) error {
	return nil
}

func (UnimplementedEventListener) OnUserAnonymized(context.Context, UserAnonymizedEvent) error {
	return nil
}

func (UnimplementedEventListener) OnRecoveryCodesRegenerated(context.Context, RecoveryCodesRegeneratedEvent) error {
	return nil
}

func (UnimplementedEventListener) OnSessionCreated(context.Context, SessionCreatedEvent) error {
	return nil
}

func (UnimplementedEventListener) OnSessionRevoked(context.Context, SessionRevokedEvent) error {
	return nil
}

func (UnimplementedEventListener) OnUserSessionsRevoked(context.Context, UserSessionsRevokedEvent) error {
	return nil
}

func (UnimplementedEventListener) OnUserLocked(context.Context, UserLockedEvent) error { return nil }

func (UnimplementedEventListener) OnPasswordResetRequested(context.Context, PasswordResetRequestedEvent) error {
	return nil
}

func (UnimplementedEventListener) OnPasswordResetCompleted(context.Context, PasswordResetCompletedEvent) error {
	return nil
}

func (UnimplementedEventListener) OnEmailAuthenticationRequested(context.Context, EmailAuthenticationRequestedEvent) error {
	return nil
}

func (UnimplementedEventListener) OnPATAuthenticated(context.Context, PATAuthenticatedEvent) error {
	return nil
}

func (UnimplementedEventListener) OnPATRejected(context.Context, PATRejectedEvent) error { return nil }

func (UnimplementedEventListener) OnSSOChallengeIssued(context.Context, SSOChallengeIssuedEvent) error {
	return nil
}

func (UnimplementedEventListener) OnSSOLinked(context.Context, SSOLinkedEvent) error { return nil }

func (UnimplementedEventListener) OnSSOUnlinked(context.Context, SSOUnlinkedEvent) error { return nil }

func (UnimplementedEventListener) OnSSOAuthenticated(context.Context, SSOAuthenticatedEvent) error {
	return nil
}

func (UnimplementedEventListener) OnSSOJITProvisioned(context.Context, SSOJITProvisionedEvent) error {
	return nil
}

func (UnimplementedEventListener) OnRoleGranted(context.Context, RoleGrantedEvent) error { return nil }

func (UnimplementedEventListener) OnInstanceRoleChanged(context.Context, InstanceRoleChangedEvent) error {
	return nil
}

func (UnimplementedEventListener) OnInstanceRoleRemoved(context.Context, InstanceRoleRemovedEvent) error {
	return nil
}

func (UnimplementedEventListener) OnClientAuditRecorded(context.Context, ClientAuditRecordedEvent) error {
	return nil
}

func (UnimplementedEventListener) OnAuditUnavailable(context.Context, AuditUnavailableEvent) error {
	return nil
}

func (UnimplementedEventListener) OnSCIMConfigurationCreated(context.Context, SCIMConfigurationCreatedEvent) error {
	return nil
}

func (UnimplementedEventListener) OnSCIMUserProvisioned(context.Context, SCIMUserEvent) error {
	return nil
}

func (UnimplementedEventListener) OnSCIMUserUpdated(context.Context, SCIMUserEvent) error { return nil }

func (UnimplementedEventListener) OnSCIMUserActivated(context.Context, SCIMUserEvent) error {
	return nil
}

func (UnimplementedEventListener) OnSCIMUserSuspended(context.Context, SCIMUserEvent) error {
	return nil
}

func (UnimplementedEventListener) OnSCIMUserDeprovisioned(context.Context, SCIMUserEvent) error {
	return nil
}

func (UnimplementedEventListener) OnSCIMGroupCreated(context.Context, SCIMGroupEvent) error {
	return nil
}

func (UnimplementedEventListener) OnSCIMGroupUpdated(context.Context, SCIMGroupEvent) error {
	return nil
}

func (UnimplementedEventListener) OnSCIMGroupDeleted(context.Context, SCIMGroupEvent) error {
	return nil
}

func (UnimplementedEventListener) OnSCIMGroupMembersChanged(context.Context, SCIMGroupEvent) error {
	return nil
}

func (UnimplementedEventListener) OnOAuthEvent(context.Context, OAuthEvent) error { return nil }
