// Command genevents generates the forward-compatible no-op implementations
// for Credbound's typed hook and event interfaces.
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/printer"
	"go/token"
	"os"
	"strings"
)

type interfaceSpec struct {
	name     string
	noOp     string
	sealName string
}

func main() {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, "events.go", nil, 0)
	if err != nil {
		panic(err)
	}

	specs := []interfaceSpec{
		{name: "TransactionHook", noOp: "UnimplementedTransactionHook", sealName: "unimplementedTransactionHook"},
		{name: "EventListener", noOp: "UnimplementedEventListener", sealName: "unimplementedEventListener"},
	}

	var output bytes.Buffer
	output.WriteString("// Code generated by internal/cmd/genevents; DO NOT EDIT.\n\n")
	output.WriteString("package credbound\n\n")
	output.WriteString("import \"context\"\n\n")
	for _, spec := range specs {
		methods := interfaceMethods(file, spec.name)
		fmt.Fprintf(&output, "type %s struct{}\n\n", spec.noOp)
		fmt.Fprintf(&output, "var _ %s = %s{}\n\n", spec.name, spec.noOp)
		fmt.Fprintf(&output, "func (%s) %s() {}\n\n", spec.noOp, spec.sealName)
		for _, method := range methods {
			var signature bytes.Buffer
			if err := printer.Fprint(&signature, fset, method.Type); err != nil {
				panic(err)
			}
			functionType := strings.TrimPrefix(signature.String(), "func")
			fmt.Fprintf(&output, "func (%s) %s%s { return nil }\n\n", spec.noOp, method.Names[0].Name, functionType)
		}
	}

	formatted, err := format.Source(output.Bytes())
	if err != nil {
		panic(fmt.Errorf("format generated events: %w\n%s", err, output.String()))
	}
	if err := os.WriteFile("events_generated.go", formatted, 0o644); err != nil {
		panic(err)
	}
	fmt.Println("events_generated.go")
}

func interfaceMethods(file *ast.File, name string) []*ast.Field {
	for _, declaration := range file.Decls {
		general, ok := declaration.(*ast.GenDecl)
		if !ok {
			continue
		}
		for _, rawSpec := range general.Specs {
			typeSpec, ok := rawSpec.(*ast.TypeSpec)
			if !ok || typeSpec.Name.Name != name {
				continue
			}
			contract, ok := typeSpec.Type.(*ast.InterfaceType)
			if !ok {
				panic(name + " is not an interface")
			}
			methods := make([]*ast.Field, 0, len(contract.Methods.List))
			for _, method := range contract.Methods.List {
				if len(method.Names) == 1 && ast.IsExported(method.Names[0].Name) {
					methods = append(methods, method)
				}
			}
			return methods
		}
	}
	panic("interface not found: " + name)
}
