-- Schema model for sqlc query analysis ONLY. It is a simplified projection and
-- is NOT the provisioning source of truth: apply migrations/postgresql/ at runtime,
-- which additionally carries partial unique indexes, immutability triggers and
-- enum CHECK constraints this file omits. Keep it in sync when migrations change.

CREATE SCHEMA credbound;
CREATE TABLE credbound.instance (singleton boolean PRIMARY KEY, initialized_at timestamptz NOT NULL);
CREATE TABLE credbound.users (id uuid PRIMARY KEY CHECK (substring(id::text from 15 for 1) = '7' AND substring(id::text from 20 for 1) IN ('8', '9', 'a', 'b')), display_name text NOT NULL, disabled boolean NOT NULL, last_seen_at timestamptz, created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL);
CREATE TABLE credbound.user_emails (id uuid PRIMARY KEY CHECK (substring(id::text from 15 for 1) = '7' AND substring(id::text from 20 for 1) IN ('8', '9', 'a', 'b')), user_id uuid NOT NULL REFERENCES credbound.users(id), address text NOT NULL UNIQUE, is_primary boolean NOT NULL, verified_at timestamptz, verification_digest bytea, verification_expires_at timestamptz, created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL);
CREATE TABLE credbound.password_credentials (user_id uuid PRIMARY KEY REFERENCES credbound.users(id), hash text NOT NULL, updated_at timestamptz NOT NULL);
CREATE TABLE credbound.workspaces (id uuid PRIMARY KEY CHECK (substring(id::text from 15 for 1) = '7' AND substring(id::text from 20 for 1) IN ('8', '9', 'a', 'b')), name text NOT NULL, created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL, disabled_at timestamptz, require_mfa boolean NOT NULL DEFAULT false);
CREATE TABLE credbound.memberships (workspace_id uuid NOT NULL REFERENCES credbound.workspaces(id), user_id uuid NOT NULL REFERENCES credbound.users(id), role text NOT NULL, status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'suspended')), provisioning_source text NOT NULL DEFAULT 'local', created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL, PRIMARY KEY (workspace_id, user_id));
CREATE TABLE credbound.instance_administrators (user_id uuid PRIMARY KEY REFERENCES credbound.users(id), role text NOT NULL, created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL);
CREATE TABLE credbound.sso_identities (id uuid PRIMARY KEY CHECK (substring(id::text from 15 for 1) = '7' AND substring(id::text from 20 for 1) IN ('8', '9', 'a', 'b')), user_id uuid NOT NULL REFERENCES credbound.users(id), provider_configuration_id uuid NOT NULL CHECK (substring(provider_configuration_id::text from 15 for 1) = '7' AND substring(provider_configuration_id::text from 20 for 1) IN ('8', '9', 'a', 'b')), provider_kind text NOT NULL, issuer text NOT NULL, subject text NOT NULL, email text NOT NULL, created_at timestamptz NOT NULL, last_used_at timestamptz, UNIQUE (provider_configuration_id, issuer, subject));
CREATE TABLE credbound.totp_factors (user_id uuid PRIMARY KEY REFERENCES credbound.users(id), encrypted_secret bytea NOT NULL, active boolean NOT NULL, last_used_step bigint NOT NULL, created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL);
CREATE TABLE credbound.recovery_codes (user_id uuid NOT NULL REFERENCES credbound.users(id), digest bytea NOT NULL, used_at timestamptz, PRIMARY KEY (user_id, digest));
CREATE TABLE credbound.passkeys (id uuid PRIMARY KEY CHECK (substring(id::text from 15 for 1) = '7' AND substring(id::text from 20 for 1) IN ('8', '9', 'a', 'b')), user_id uuid NOT NULL REFERENCES credbound.users(id), name text NOT NULL, credential_id bytea NOT NULL UNIQUE, credential_json bytea NOT NULL, created_at timestamptz NOT NULL, last_used_at timestamptz);
CREATE TABLE credbound.personal_access_tokens (id uuid PRIMARY KEY CHECK (substring(id::text from 15 for 1) = '7' AND substring(id::text from 20 for 1) IN ('8', '9', 'a', 'b')), user_id uuid NOT NULL REFERENCES credbound.users(id), name text NOT NULL, prefix text NOT NULL UNIQUE, digest bytea NOT NULL, workspace_id uuid REFERENCES credbound.workspaces(id), scopes_json jsonb NOT NULL, created_at timestamptz NOT NULL, expires_at timestamptz, last_used_at timestamptz, revoked_at timestamptz);
CREATE TABLE credbound.audit_events (id uuid PRIMARY KEY CHECK (substring(id::text from 15 for 1) = '7' AND substring(id::text from 20 for 1) IN ('8', '9', 'a', 'b')), occurred_at timestamptz NOT NULL, actor_kind text NOT NULL DEFAULT 'user' CHECK (actor_kind IN ('user', 'service', 'system')), actor_id uuid, action text NOT NULL, resource_type text NOT NULL, resource_id text NOT NULL, workspace_id uuid, outcome text NOT NULL, reason text NOT NULL, ip_address text NOT NULL DEFAULT '', user_agent text NOT NULL DEFAULT '', sequence bigint, previous_hash bytea, hash bytea);
CREATE UNIQUE INDEX audit_events_sequence_idx ON credbound.audit_events(sequence) WHERE sequence IS NOT NULL;
CREATE TABLE credbound.audit_chain (singleton integer PRIMARY KEY CHECK (singleton = 1), sequence bigint NOT NULL, head_hash bytea NOT NULL);
CREATE TABLE credbound.login_throttles (user_id uuid PRIMARY KEY REFERENCES credbound.users(id), failed_attempts bigint NOT NULL, locked_until timestamptz, updated_at timestamptz NOT NULL);
CREATE TABLE credbound.email_issuance (address TEXT NOT NULL, purpose TEXT NOT NULL, last_issued_at timestamptz NOT NULL, PRIMARY KEY (address, purpose));
CREATE TABLE credbound.password_resets (id uuid PRIMARY KEY CHECK (substring(id::text from 15 for 1) = '7' AND substring(id::text from 20 for 1) IN ('8', '9', 'a', 'b')), user_id uuid NOT NULL REFERENCES credbound.users(id), digest bytea NOT NULL, created_at timestamptz NOT NULL, expires_at timestamptz NOT NULL, used_at timestamptz);
CREATE INDEX password_resets_user_idx ON credbound.password_resets(user_id);
CREATE TABLE credbound.email_authentications (id uuid PRIMARY KEY CHECK (substring(id::text from 15 for 1) = '7' AND substring(id::text from 20 for 1) IN ('8', '9', 'a', 'b')), user_id uuid NOT NULL REFERENCES credbound.users(id), email_id uuid NOT NULL REFERENCES credbound.user_emails(id), digest bytea NOT NULL, created_at timestamptz NOT NULL, expires_at timestamptz NOT NULL, used_at timestamptz);
CREATE INDEX email_authentications_user_idx ON credbound.email_authentications(user_id);
CREATE TABLE credbound.workspace_invitations (id uuid PRIMARY KEY CHECK (substring(id::text from 15 for 1) = '7' AND substring(id::text from 20 for 1) IN ('8', '9', 'a', 'b')), workspace_id uuid NOT NULL REFERENCES credbound.workspaces(id), email text NOT NULL, role text NOT NULL, invited_by uuid NOT NULL REFERENCES credbound.users(id), digest bytea NOT NULL, created_at timestamptz NOT NULL, expires_at timestamptz NOT NULL, accepted_at timestamptz, accepted_user_id uuid, revoked_at timestamptz);
CREATE UNIQUE INDEX workspace_invitations_pending_idx ON credbound.workspace_invitations(workspace_id, email) WHERE accepted_at IS NULL AND revoked_at IS NULL;
CREATE INDEX workspace_invitations_page_idx ON credbound.workspace_invitations(workspace_id, created_at DESC, id DESC);
CREATE TABLE credbound.scim_configurations (id uuid PRIMARY KEY CHECK (substring(id::text from 15 for 1) = '7' AND substring(id::text from 20 for 1) IN ('8', '9', 'a', 'b')), workspace_id uuid NOT NULL REFERENCES credbound.workspaces(id), enabled boolean NOT NULL, default_role text NOT NULL, trust_directory_emails boolean NOT NULL, group_role_mappings_json jsonb NOT NULL, created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL);
CREATE INDEX scim_configurations_workspace_idx ON credbound.scim_configurations(workspace_id);
CREATE TABLE credbound.scim_credentials (id uuid PRIMARY KEY CHECK (substring(id::text from 15 for 1) = '7' AND substring(id::text from 20 for 1) IN ('8', '9', 'a', 'b')), configuration_id uuid NOT NULL REFERENCES credbound.scim_configurations(id), prefix text NOT NULL UNIQUE, digest bytea NOT NULL, created_at timestamptz NOT NULL, expires_at timestamptz, last_used_at timestamptz, revoked_at timestamptz);
CREATE INDEX scim_credentials_configuration_idx ON credbound.scim_credentials(configuration_id);
CREATE TABLE credbound.scim_users (id uuid PRIMARY KEY CHECK (substring(id::text from 15 for 1) = '7' AND substring(id::text from 20 for 1) IN ('8', '9', 'a', 'b')), configuration_id uuid NOT NULL REFERENCES credbound.scim_configurations(id), user_id uuid NOT NULL REFERENCES credbound.users(id), external_id text, normalized_user_name text NOT NULL, display_name text NOT NULL, emails_json jsonb NOT NULL, profile_json jsonb NOT NULL, active boolean NOT NULL, created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL, deprovisioned_at timestamptz, UNIQUE (configuration_id, user_id), UNIQUE (configuration_id, normalized_user_name));
CREATE UNIQUE INDEX scim_users_external_id_idx ON credbound.scim_users(configuration_id, external_id) WHERE external_id IS NOT NULL;
CREATE INDEX scim_users_page_idx ON credbound.scim_users(configuration_id, created_at DESC, id DESC);
CREATE TABLE credbound.scim_groups (id uuid PRIMARY KEY CHECK (substring(id::text from 15 for 1) = '7' AND substring(id::text from 20 for 1) IN ('8', '9', 'a', 'b')), configuration_id uuid NOT NULL REFERENCES credbound.scim_configurations(id), external_id text, display_name text NOT NULL, member_ids_json jsonb NOT NULL, created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL, deleted_at timestamptz);
CREATE UNIQUE INDEX scim_groups_external_id_idx ON credbound.scim_groups(configuration_id, external_id) WHERE external_id IS NOT NULL AND deleted_at IS NULL;
CREATE INDEX scim_groups_page_idx ON credbound.scim_groups(configuration_id, created_at DESC, id DESC);
CREATE TABLE credbound.oauth_issuers (id uuid PRIMARY KEY CHECK (substring(id::text from 15 for 1) = '7' AND substring(id::text from 20 for 1) IN ('8', '9', 'a', 'b')), issuer text NOT NULL UNIQUE, created_at timestamptz NOT NULL, data_json jsonb NOT NULL);
CREATE TABLE credbound.oauth_resources (id uuid PRIMARY KEY CHECK (substring(id::text from 15 for 1) = '7' AND substring(id::text from 20 for 1) IN ('8', '9', 'a', 'b')), issuer_id uuid NOT NULL REFERENCES credbound.oauth_issuers(id), workspace_id uuid NOT NULL REFERENCES credbound.workspaces(id), resource text NOT NULL UNIQUE, created_at timestamptz NOT NULL, data_json jsonb NOT NULL);
CREATE TABLE credbound.oauth_clients (id uuid PRIMARY KEY CHECK (substring(id::text from 15 for 1) = '7' AND substring(id::text from 20 for 1) IN ('8', '9', 'a', 'b')), issuer_id uuid NOT NULL REFERENCES credbound.oauth_issuers(id), client_id text NOT NULL, created_at timestamptz NOT NULL, data_json jsonb NOT NULL, UNIQUE (issuer_id, client_id));
CREATE TABLE credbound.oauth_initial_access_tokens (id uuid PRIMARY KEY CHECK (substring(id::text from 15 for 1) = '7' AND substring(id::text from 20 for 1) IN ('8', '9', 'a', 'b')), issuer_id uuid NOT NULL REFERENCES credbound.oauth_issuers(id), prefix text NOT NULL UNIQUE, registration_count integer NOT NULL, max_registrations integer NOT NULL, expires_at timestamptz NOT NULL, revoked_at timestamptz, data_json jsonb NOT NULL);
CREATE TABLE credbound.oauth_grants (id uuid PRIMARY KEY CHECK (substring(id::text from 15 for 1) = '7' AND substring(id::text from 20 for 1) IN ('8', '9', 'a', 'b')), client_record_id uuid NOT NULL REFERENCES credbound.oauth_clients(id), resource_id uuid NOT NULL REFERENCES credbound.oauth_resources(id), user_id uuid NOT NULL REFERENCES credbound.users(id), workspace_id uuid NOT NULL REFERENCES credbound.workspaces(id), created_at timestamptz NOT NULL, data_json jsonb NOT NULL);
CREATE TABLE credbound.oauth_authorization_codes (id uuid PRIMARY KEY CHECK (substring(id::text from 15 for 1) = '7' AND substring(id::text from 20 for 1) IN ('8', '9', 'a', 'b')), prefix text NOT NULL UNIQUE, grant_id uuid NOT NULL REFERENCES credbound.oauth_grants(id), used_at timestamptz, expires_at timestamptz NOT NULL, data_json jsonb NOT NULL);
CREATE TABLE credbound.oauth_access_tokens (id uuid PRIMARY KEY CHECK (substring(id::text from 15 for 1) = '7' AND substring(id::text from 20 for 1) IN ('8', '9', 'a', 'b')), prefix text NOT NULL UNIQUE, grant_id uuid NOT NULL REFERENCES credbound.oauth_grants(id), data_json jsonb NOT NULL);
CREATE TABLE credbound.oauth_client_access_tokens (id uuid PRIMARY KEY CHECK (substring(id::text from 15 for 1) = '7' AND substring(id::text from 20 for 1) IN ('8', '9', 'a', 'b')), prefix text NOT NULL UNIQUE, client_record_id uuid NOT NULL REFERENCES credbound.oauth_clients(id), data_json jsonb NOT NULL);
CREATE TABLE credbound.oauth_refresh_tokens (id uuid PRIMARY KEY CHECK (substring(id::text from 15 for 1) = '7' AND substring(id::text from 20 for 1) IN ('8', '9', 'a', 'b')), family_id uuid NOT NULL CHECK (substring(family_id::text from 15 for 1) = '7' AND substring(family_id::text from 20 for 1) IN ('8', '9', 'a', 'b')), prefix text NOT NULL UNIQUE, grant_id uuid NOT NULL REFERENCES credbound.oauth_grants(id), used_at timestamptz, revoked_at timestamptz, expires_at timestamptz NOT NULL, data_json jsonb NOT NULL);
CREATE INDEX oauth_refresh_family_idx ON credbound.oauth_refresh_tokens(family_id);
CREATE TABLE credbound.sessions (id uuid PRIMARY KEY CHECK (substring(id::text from 15 for 1) = '7' AND substring(id::text from 20 for 1) IN ('8', '9', 'a', 'b')), user_id uuid NOT NULL REFERENCES credbound.users(id), method text NOT NULL, level smallint NOT NULL, authenticated_at timestamptz NOT NULL, second_factor_required boolean NOT NULL DEFAULT false, user_agent text NOT NULL DEFAULT '', ip_address text NOT NULL DEFAULT '', digest bytea NOT NULL, created_at timestamptz NOT NULL, last_seen_at timestamptz NOT NULL, expires_at timestamptz NOT NULL, revoked_at timestamptz);
CREATE INDEX sessions_user_idx ON credbound.sessions(user_id, created_at DESC, id DESC);
CREATE TABLE credbound.workspace_domains (id uuid PRIMARY KEY CHECK (substring(id::text from 15 for 1) = '7' AND substring(id::text from 20 for 1) IN ('8', '9', 'a', 'b')), workspace_id uuid NOT NULL REFERENCES credbound.workspaces(id), domain text NOT NULL UNIQUE, challenge text NOT NULL, confirmed_at timestamptz, auto_join boolean NOT NULL DEFAULT false, auto_join_role text NOT NULL DEFAULT '', sso_provider_configuration_id text NOT NULL DEFAULT '', enforce_sso boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL);
CREATE INDEX workspace_domains_workspace_idx ON credbound.workspace_domains(workspace_id, created_at DESC, id DESC);
CREATE TABLE credbound.consumed_ceremonies (id uuid PRIMARY KEY CHECK (substring(id::text from 15 for 1) = '7' AND substring(id::text from 20 for 1) IN ('8', '9', 'a', 'b')), expires_at timestamptz NOT NULL);
