-- Schema model for sqlc query analysis ONLY. It is a simplified projection and
-- is NOT the provisioning source of truth: apply migrations/sqlite/ at runtime,
-- which additionally carries partial unique indexes, immutability triggers and
-- enum CHECK constraints this file omits. Keep it in sync when migrations change.

CREATE TABLE credbound_instance (singleton INTEGER PRIMARY KEY, initialized_at DATETIME NOT NULL);
CREATE TABLE credbound_users (id TEXT PRIMARY KEY CHECK (length(id) = 36 AND id = lower(id) AND substr(id, 15, 1) = '7' AND substr(id, 20, 1) GLOB '[89ab]' AND replace(id, '-', '') NOT GLOB '*[^0-9a-f]*'), display_name TEXT NOT NULL, disabled INTEGER NOT NULL, last_seen_at DATETIME, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL);
CREATE TABLE credbound_user_emails (id TEXT PRIMARY KEY CHECK (length(id) = 36 AND id = lower(id) AND substr(id, 15, 1) = '7' AND substr(id, 20, 1) GLOB '[89ab]' AND replace(id, '-', '') NOT GLOB '*[^0-9a-f]*'), user_id TEXT NOT NULL REFERENCES credbound_users(id), address TEXT NOT NULL UNIQUE, is_primary INTEGER NOT NULL, verified_at DATETIME, verification_digest BLOB, verification_expires_at DATETIME, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL);
CREATE TABLE credbound_password_credentials (user_id TEXT PRIMARY KEY REFERENCES credbound_users(id), hash TEXT NOT NULL, updated_at DATETIME NOT NULL);
CREATE TABLE credbound_workspaces (id TEXT PRIMARY KEY CHECK (length(id) = 36 AND id = lower(id) AND substr(id, 15, 1) = '7' AND substr(id, 20, 1) GLOB '[89ab]' AND replace(id, '-', '') NOT GLOB '*[^0-9a-f]*'), name TEXT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, disabled_at DATETIME, require_mfa INTEGER NOT NULL DEFAULT 0);
CREATE TABLE credbound_memberships (workspace_id TEXT NOT NULL REFERENCES credbound_workspaces(id), user_id TEXT NOT NULL REFERENCES credbound_users(id), role TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'suspended')), provisioning_source TEXT NOT NULL DEFAULT 'local', created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY (workspace_id, user_id));
CREATE TABLE credbound_instance_administrators (user_id TEXT PRIMARY KEY REFERENCES credbound_users(id), role TEXT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL);
CREATE TABLE credbound_sso_identities (id TEXT PRIMARY KEY CHECK (length(id) = 36 AND id = lower(id) AND substr(id, 15, 1) = '7' AND substr(id, 20, 1) GLOB '[89ab]' AND replace(id, '-', '') NOT GLOB '*[^0-9a-f]*'), user_id TEXT NOT NULL REFERENCES credbound_users(id), provider_configuration_id TEXT NOT NULL CHECK (length(provider_configuration_id) = 36 AND provider_configuration_id = lower(provider_configuration_id) AND substr(provider_configuration_id, 15, 1) = '7' AND substr(provider_configuration_id, 20, 1) GLOB '[89ab]' AND replace(provider_configuration_id, '-', '') NOT GLOB '*[^0-9a-f]*'), provider_kind TEXT NOT NULL, issuer TEXT NOT NULL, subject TEXT NOT NULL, email TEXT NOT NULL, created_at DATETIME NOT NULL, last_used_at DATETIME, UNIQUE (provider_configuration_id, issuer, subject));
CREATE TABLE credbound_totp_factors (user_id TEXT PRIMARY KEY REFERENCES credbound_users(id), encrypted_secret BLOB NOT NULL, active INTEGER NOT NULL, last_used_step INTEGER NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL);
CREATE TABLE credbound_recovery_codes (user_id TEXT NOT NULL REFERENCES credbound_users(id), digest BLOB NOT NULL, used_at DATETIME, PRIMARY KEY (user_id, digest));
CREATE TABLE credbound_passkeys (id TEXT PRIMARY KEY CHECK (length(id) = 36 AND id = lower(id) AND substr(id, 15, 1) = '7' AND substr(id, 20, 1) GLOB '[89ab]' AND replace(id, '-', '') NOT GLOB '*[^0-9a-f]*'), user_id TEXT NOT NULL REFERENCES credbound_users(id), name TEXT NOT NULL, credential_id BLOB NOT NULL UNIQUE, credential_json BLOB NOT NULL, created_at DATETIME NOT NULL, last_used_at DATETIME);
CREATE TABLE credbound_personal_access_tokens (id TEXT PRIMARY KEY CHECK (length(id) = 36 AND id = lower(id) AND substr(id, 15, 1) = '7' AND substr(id, 20, 1) GLOB '[89ab]' AND replace(id, '-', '') NOT GLOB '*[^0-9a-f]*'), user_id TEXT NOT NULL REFERENCES credbound_users(id), name TEXT NOT NULL, prefix TEXT NOT NULL UNIQUE, digest BLOB NOT NULL, workspace_id TEXT, scopes_json TEXT NOT NULL, created_at DATETIME NOT NULL, expires_at DATETIME, last_used_at DATETIME, revoked_at DATETIME);
CREATE TABLE credbound_audit_events (id TEXT PRIMARY KEY CHECK (length(id) = 36 AND id = lower(id) AND substr(id, 15, 1) = '7' AND substr(id, 20, 1) GLOB '[89ab]' AND replace(id, '-', '') NOT GLOB '*[^0-9a-f]*'), occurred_at DATETIME NOT NULL, actor_kind TEXT NOT NULL DEFAULT 'user' CHECK (actor_kind IN ('user', 'service', 'system')), actor_id TEXT, action TEXT NOT NULL, resource_type TEXT NOT NULL, resource_id TEXT NOT NULL, workspace_id TEXT, outcome TEXT NOT NULL, reason TEXT NOT NULL, ip_address TEXT NOT NULL DEFAULT '', user_agent TEXT NOT NULL DEFAULT '', sequence INTEGER, previous_hash BLOB, hash BLOB);
CREATE UNIQUE INDEX credbound_audit_events_sequence_idx ON credbound_audit_events(sequence) WHERE sequence IS NOT NULL;
CREATE TABLE credbound_audit_chain (singleton INTEGER PRIMARY KEY CHECK (singleton = 1), sequence INTEGER NOT NULL, head_hash BLOB NOT NULL);
CREATE TABLE credbound_login_throttles (user_id TEXT PRIMARY KEY REFERENCES credbound_users(id), failed_attempts INTEGER NOT NULL, locked_until DATETIME, updated_at DATETIME NOT NULL);
CREATE TABLE credbound_email_issuance (address TEXT NOT NULL, purpose TEXT NOT NULL, last_issued_at DATETIME NOT NULL, PRIMARY KEY (address, purpose));
CREATE TABLE credbound_password_resets (id TEXT PRIMARY KEY CHECK (length(id) = 36 AND id = lower(id) AND substr(id, 15, 1) = '7' AND substr(id, 20, 1) GLOB '[89ab]' AND replace(id, '-', '') NOT GLOB '*[^0-9a-f]*'), user_id TEXT NOT NULL REFERENCES credbound_users(id), digest BLOB NOT NULL, created_at DATETIME NOT NULL, expires_at DATETIME NOT NULL, used_at DATETIME);
CREATE INDEX credbound_password_resets_user_idx ON credbound_password_resets(user_id);
CREATE TABLE credbound_email_authentications (id TEXT PRIMARY KEY CHECK (length(id) = 36 AND id = lower(id) AND substr(id, 15, 1) = '7' AND substr(id, 20, 1) GLOB '[89ab]' AND replace(id, '-', '') NOT GLOB '*[^0-9a-f]*'), user_id TEXT NOT NULL REFERENCES credbound_users(id), email_id TEXT NOT NULL REFERENCES credbound_user_emails(id), digest BLOB NOT NULL, created_at DATETIME NOT NULL, expires_at DATETIME NOT NULL, used_at DATETIME);
CREATE INDEX credbound_email_authentications_user_idx ON credbound_email_authentications(user_id);
CREATE TABLE credbound_workspace_invitations (id TEXT PRIMARY KEY CHECK (length(id) = 36 AND id = lower(id) AND substr(id, 15, 1) = '7' AND substr(id, 20, 1) GLOB '[89ab]' AND replace(id, '-', '') NOT GLOB '*[^0-9a-f]*'), workspace_id TEXT NOT NULL REFERENCES credbound_workspaces(id), email TEXT NOT NULL, role TEXT NOT NULL, invited_by TEXT NOT NULL REFERENCES credbound_users(id), digest BLOB NOT NULL, created_at DATETIME NOT NULL, expires_at DATETIME NOT NULL, accepted_at DATETIME, accepted_user_id TEXT, revoked_at DATETIME);
CREATE UNIQUE INDEX credbound_workspace_invitations_pending_idx ON credbound_workspace_invitations(workspace_id, email) WHERE accepted_at IS NULL AND revoked_at IS NULL;
CREATE INDEX credbound_workspace_invitations_page_idx ON credbound_workspace_invitations(workspace_id, created_at DESC, id DESC);
CREATE TABLE credbound_scim_configurations (id TEXT PRIMARY KEY CHECK (length(id) = 36 AND id = lower(id) AND substr(id, 15, 1) = '7' AND substr(id, 20, 1) GLOB '[89ab]' AND replace(id, '-', '') NOT GLOB '*[^0-9a-f]*'), workspace_id TEXT NOT NULL REFERENCES credbound_workspaces(id), enabled INTEGER NOT NULL, default_role TEXT NOT NULL, trust_directory_emails INTEGER NOT NULL, group_role_mappings_json TEXT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL);
CREATE INDEX credbound_scim_configurations_workspace_idx ON credbound_scim_configurations(workspace_id);
CREATE TABLE credbound_scim_credentials (id TEXT PRIMARY KEY CHECK (length(id) = 36 AND id = lower(id) AND substr(id, 15, 1) = '7' AND substr(id, 20, 1) GLOB '[89ab]' AND replace(id, '-', '') NOT GLOB '*[^0-9a-f]*'), configuration_id TEXT NOT NULL REFERENCES credbound_scim_configurations(id), prefix TEXT NOT NULL UNIQUE, digest BLOB NOT NULL, created_at DATETIME NOT NULL, expires_at DATETIME, last_used_at DATETIME, revoked_at DATETIME);
CREATE INDEX credbound_scim_credentials_configuration_idx ON credbound_scim_credentials(configuration_id);
CREATE TABLE credbound_scim_users (id TEXT PRIMARY KEY CHECK (length(id) = 36 AND id = lower(id) AND substr(id, 15, 1) = '7' AND substr(id, 20, 1) GLOB '[89ab]' AND replace(id, '-', '') NOT GLOB '*[^0-9a-f]*'), configuration_id TEXT NOT NULL REFERENCES credbound_scim_configurations(id), user_id TEXT NOT NULL REFERENCES credbound_users(id), external_id TEXT, normalized_user_name TEXT NOT NULL, display_name TEXT NOT NULL, emails_json TEXT NOT NULL, profile_json TEXT NOT NULL, active INTEGER NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, deprovisioned_at DATETIME, UNIQUE (configuration_id, user_id), UNIQUE (configuration_id, normalized_user_name));
CREATE UNIQUE INDEX credbound_scim_users_external_id_idx ON credbound_scim_users(configuration_id, external_id) WHERE external_id IS NOT NULL;
CREATE INDEX credbound_scim_users_page_idx ON credbound_scim_users(configuration_id, created_at DESC, id DESC);
CREATE TABLE credbound_scim_groups (id TEXT PRIMARY KEY CHECK (length(id) = 36 AND id = lower(id) AND substr(id, 15, 1) = '7' AND substr(id, 20, 1) GLOB '[89ab]' AND replace(id, '-', '') NOT GLOB '*[^0-9a-f]*'), configuration_id TEXT NOT NULL REFERENCES credbound_scim_configurations(id), external_id TEXT, display_name TEXT NOT NULL, member_ids_json TEXT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, deleted_at DATETIME);
CREATE UNIQUE INDEX credbound_scim_groups_external_id_idx ON credbound_scim_groups(configuration_id, external_id) WHERE external_id IS NOT NULL AND deleted_at IS NULL;
CREATE INDEX credbound_scim_groups_page_idx ON credbound_scim_groups(configuration_id, created_at DESC, id DESC);
CREATE TABLE credbound_oauth_issuers (id TEXT PRIMARY KEY CHECK (length(id) = 36 AND id = lower(id) AND substr(id, 15, 1) = '7' AND substr(id, 20, 1) GLOB '[89ab]' AND replace(id, '-', '') NOT GLOB '*[^0-9a-f]*'), issuer TEXT NOT NULL UNIQUE, created_at DATETIME NOT NULL, data_json TEXT NOT NULL);
CREATE TABLE credbound_oauth_resources (id TEXT PRIMARY KEY CHECK (length(id) = 36 AND id = lower(id) AND substr(id, 15, 1) = '7' AND substr(id, 20, 1) GLOB '[89ab]' AND replace(id, '-', '') NOT GLOB '*[^0-9a-f]*'), issuer_id TEXT NOT NULL REFERENCES credbound_oauth_issuers(id), workspace_id TEXT NOT NULL REFERENCES credbound_workspaces(id), resource TEXT NOT NULL UNIQUE, created_at DATETIME NOT NULL, data_json TEXT NOT NULL);
CREATE TABLE credbound_oauth_clients (id TEXT PRIMARY KEY CHECK (length(id) = 36 AND id = lower(id) AND substr(id, 15, 1) = '7' AND substr(id, 20, 1) GLOB '[89ab]' AND replace(id, '-', '') NOT GLOB '*[^0-9a-f]*'), issuer_id TEXT NOT NULL REFERENCES credbound_oauth_issuers(id), client_id TEXT NOT NULL, created_at DATETIME NOT NULL, data_json TEXT NOT NULL, UNIQUE (issuer_id, client_id));
CREATE TABLE credbound_oauth_initial_access_tokens (id TEXT PRIMARY KEY CHECK (length(id) = 36 AND id = lower(id) AND substr(id, 15, 1) = '7' AND substr(id, 20, 1) GLOB '[89ab]' AND replace(id, '-', '') NOT GLOB '*[^0-9a-f]*'), issuer_id TEXT NOT NULL REFERENCES credbound_oauth_issuers(id), prefix TEXT NOT NULL UNIQUE, registration_count INTEGER NOT NULL, max_registrations INTEGER NOT NULL, expires_at DATETIME NOT NULL, revoked_at DATETIME, data_json TEXT NOT NULL);
CREATE TABLE credbound_oauth_grants (id TEXT PRIMARY KEY CHECK (length(id) = 36 AND id = lower(id) AND substr(id, 15, 1) = '7' AND substr(id, 20, 1) GLOB '[89ab]' AND replace(id, '-', '') NOT GLOB '*[^0-9a-f]*'), client_record_id TEXT NOT NULL REFERENCES credbound_oauth_clients(id), resource_id TEXT NOT NULL REFERENCES credbound_oauth_resources(id), user_id TEXT NOT NULL REFERENCES credbound_users(id), workspace_id TEXT NOT NULL REFERENCES credbound_workspaces(id), created_at DATETIME NOT NULL, data_json TEXT NOT NULL);
CREATE TABLE credbound_oauth_authorization_codes (id TEXT PRIMARY KEY CHECK (length(id) = 36 AND id = lower(id) AND substr(id, 15, 1) = '7' AND substr(id, 20, 1) GLOB '[89ab]' AND replace(id, '-', '') NOT GLOB '*[^0-9a-f]*'), prefix TEXT NOT NULL UNIQUE, grant_id TEXT NOT NULL REFERENCES credbound_oauth_grants(id), used_at DATETIME, expires_at DATETIME NOT NULL, data_json TEXT NOT NULL);
CREATE TABLE credbound_oauth_access_tokens (id TEXT PRIMARY KEY CHECK (length(id) = 36 AND id = lower(id) AND substr(id, 15, 1) = '7' AND substr(id, 20, 1) GLOB '[89ab]' AND replace(id, '-', '') NOT GLOB '*[^0-9a-f]*'), prefix TEXT NOT NULL UNIQUE, grant_id TEXT NOT NULL REFERENCES credbound_oauth_grants(id), data_json TEXT NOT NULL);
CREATE TABLE credbound_oauth_client_access_tokens (id TEXT PRIMARY KEY CHECK (length(id) = 36 AND id = lower(id) AND substr(id, 15, 1) = '7' AND substr(id, 20, 1) GLOB '[89ab]' AND replace(id, '-', '') NOT GLOB '*[^0-9a-f]*'), prefix TEXT NOT NULL UNIQUE, client_record_id TEXT NOT NULL REFERENCES credbound_oauth_clients(id), data_json TEXT NOT NULL);
CREATE TABLE credbound_oauth_refresh_tokens (id TEXT PRIMARY KEY CHECK (length(id) = 36 AND id = lower(id) AND substr(id, 15, 1) = '7' AND substr(id, 20, 1) GLOB '[89ab]' AND replace(id, '-', '') NOT GLOB '*[^0-9a-f]*'), family_id TEXT NOT NULL CHECK (length(family_id) = 36 AND family_id = lower(family_id) AND substr(family_id, 15, 1) = '7' AND substr(family_id, 20, 1) GLOB '[89ab]' AND replace(family_id, '-', '') NOT GLOB '*[^0-9a-f]*'), prefix TEXT NOT NULL UNIQUE, grant_id TEXT NOT NULL REFERENCES credbound_oauth_grants(id), used_at DATETIME, revoked_at DATETIME, expires_at DATETIME NOT NULL, data_json TEXT NOT NULL);
CREATE INDEX credbound_oauth_refresh_family_idx ON credbound_oauth_refresh_tokens(family_id);
CREATE TABLE credbound_sessions (id TEXT PRIMARY KEY CHECK (length(id) = 36 AND id = lower(id) AND substr(id, 15, 1) = '7' AND substr(id, 20, 1) GLOB '[89ab]' AND replace(id, '-', '') NOT GLOB '*[^0-9a-f]*'), user_id TEXT NOT NULL REFERENCES credbound_users(id), method TEXT NOT NULL, level INTEGER NOT NULL, authenticated_at DATETIME NOT NULL, second_factor_required INTEGER NOT NULL DEFAULT 0, user_agent TEXT NOT NULL DEFAULT '', ip_address TEXT NOT NULL DEFAULT '', digest BLOB NOT NULL, created_at DATETIME NOT NULL, last_seen_at DATETIME NOT NULL, expires_at DATETIME NOT NULL, revoked_at DATETIME);
CREATE INDEX credbound_sessions_user_idx ON credbound_sessions(user_id, created_at DESC, id DESC);
CREATE TABLE credbound_workspace_domains (id TEXT PRIMARY KEY CHECK (length(id) = 36 AND id = lower(id) AND substr(id, 15, 1) = '7' AND substr(id, 20, 1) GLOB '[89ab]' AND replace(id, '-', '') NOT GLOB '*[^0-9a-f]*'), workspace_id TEXT NOT NULL REFERENCES credbound_workspaces(id), domain TEXT NOT NULL UNIQUE, challenge TEXT NOT NULL, confirmed_at DATETIME, auto_join INTEGER NOT NULL DEFAULT 0, auto_join_role TEXT NOT NULL DEFAULT '', sso_provider_configuration_id TEXT NOT NULL DEFAULT '', enforce_sso INTEGER NOT NULL DEFAULT 0, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL);
CREATE INDEX credbound_workspace_domains_workspace_idx ON credbound_workspace_domains(workspace_id, created_at DESC, id DESC);
CREATE TABLE credbound_consumed_ceremonies (id TEXT PRIMARY KEY CHECK (length(id) = 36 AND id = lower(id) AND substr(id, 15, 1) = '7' AND substr(id, 20, 1) GLOB '[89ab]' AND replace(id, '-', '') NOT GLOB '*[^0-9a-f]*'), expires_at DATETIME NOT NULL);

-- Index added for query paths that had no usable index (see the audit in
-- ADR-003): user-scoped lookups behind composite keys, revocation cascades,
-- the ceremony prune, and the unfiltered listings' ordering.
CREATE INDEX credbound_users_page_idx ON credbound_users(created_at DESC, id DESC);
CREATE INDEX credbound_workspaces_page_idx ON credbound_workspaces(created_at DESC, id DESC);
CREATE INDEX credbound_memberships_user_idx ON credbound_memberships(user_id);
CREATE INDEX credbound_pats_workspace_idx ON credbound_personal_access_tokens(workspace_id) WHERE workspace_id IS NOT NULL;
CREATE INDEX credbound_scim_users_user_idx ON credbound_scim_users(user_id);
CREATE INDEX credbound_workspace_invitations_accepted_user_idx ON credbound_workspace_invitations(accepted_user_id) WHERE accepted_user_id IS NOT NULL;
CREATE INDEX credbound_oauth_access_tokens_grant_idx ON credbound_oauth_access_tokens(grant_id);
CREATE INDEX credbound_oauth_refresh_grant_idx ON credbound_oauth_refresh_tokens(grant_id);
CREATE INDEX credbound_oauth_grants_client_idx ON credbound_oauth_grants(client_record_id);
CREATE INDEX credbound_oauth_grants_resource_idx ON credbound_oauth_grants(resource_id);
CREATE INDEX credbound_oauth_grants_created_idx ON credbound_oauth_grants(created_at DESC, id DESC);
CREATE INDEX credbound_oauth_initial_access_tokens_issuer_idx ON credbound_oauth_initial_access_tokens(issuer_id);
CREATE INDEX credbound_consumed_ceremonies_expiry_idx ON credbound_consumed_ceremonies(expires_at);
