// Package postgresql implements every Credbound persistence port — Store
// plus the optional SessionStore, SignupStore, DomainStore, SCIMStore,
// EmailThrottleStore and OAuthStore capabilities — on PostgreSQL, pairing
// sqlc-generated database/sql queries for transactional mutations with pgx
// streaming for paginated reads, and committing each mutation's hash-chained
// audit event atomically with the change.
//
// All objects live in the dedicated "credbound" schema; apply the module's
// migrations before use. Open one pgx pool and hand the store both views of
// it, then wire the store into credbound.Config.Store:
//
//	pool, err := pgxpool.New(ctx, dsn)
//	store, err := postgresql.New(stdlib.OpenDBFromPool(pool), pool)
//
// TransactionHook callbacks can regain the raw *sql.Tx through TxFrom to
// append host writes to a Credbound commit.
//
// Statements are written for PostgreSQL directly: typed uuid parameters, jsonb
// operators, and SELECT … FOR UPDATE for the read-then-write invariants. The
// transactional ones are generated by sqlc from sql/queries/postgresql.sql;
// the paginated reads, which sqlc cannot express, live in queries.go.
package postgresql
