// Code generated by internal/cmd/genpostgresstore; DO NOT EDIT.
package postgresql

import (
	"context"
	"database/sql"
	"encoding/json"
	"fmt"
	"iter"
	"strings"
	"time"

	"github.com/deepteams/credbound"
	db "github.com/deepteams/credbound/internal/sqlc/postgresql"
)

func (s *Store) CreateSCIMConfiguration(ctx context.Context, configuration credbound.SCIMConfiguration, credential credbound.SCIMCredential, commit credbound.Commit) error {
	return s.mutate(ctx, commit, func(q *db.Queries) error {
		if err := insertSCIMConfiguration(ctx, q, configuration); err != nil {
			return err
		}
		return insertSCIMCredential(ctx, q, credential)
	})
}

func (s *Store) SCIMConfiguration(ctx context.Context, id string) (credbound.SCIMConfiguration, error) {
	row, err := s.queries.GetSCIMConfiguration(ctx, id)
	if err != nil {
		return credbound.SCIMConfiguration{}, mapError(err)
	}
	return scimConfigurationFromRow(row)
}

func (s *Store) UpdateSCIMConfiguration(ctx context.Context, configuration credbound.SCIMConfiguration, memberships []credbound.Membership, commit credbound.Commit) error {
	return s.mutate(ctx, commit, func(q *db.Queries) error {
		mappings, err := json.Marshal(configuration.GroupRoleMappings)
		if err != nil {
			return err
		}
		count, err := q.UpdateSCIMConfiguration(ctx, db.UpdateSCIMConfigurationParams{
			ID: configuration.ID, DefaultRole: string(configuration.DefaultRole), TrustDirectoryEmails: sqlBool(configuration.TrustDirectoryEmails),
			GroupRoleMappingsJson: mappings, UpdatedAt: configuration.UpdatedAt, WorkspaceID: configuration.WorkspaceID,
		})
		if err := affected(count, err); err != nil {
			return err
		}
		for _, membership := range memberships {
			if err := upsertMembership(ctx, q, membership); err != nil {
				return err
			}
		}
		return nil
	})
}

func (s *Store) SCIMConfigurationByCredentialPrefix(ctx context.Context, prefix string) (credbound.SCIMConfiguration, credbound.SCIMCredential, error) {
	row, err := s.queries.GetSCIMConfigurationByCredentialPrefix(ctx, prefix)
	if err != nil {
		return credbound.SCIMConfiguration{}, credbound.SCIMCredential{}, mapError(err)
	}
	configuration, err := scimConfigurationFromCredentialRow(row)
	if err != nil {
		return credbound.SCIMConfiguration{}, credbound.SCIMCredential{}, err
	}
	credential := credbound.SCIMCredential{
		ID: row.CredentialID, ConfigurationID: row.ConfigurationID, Prefix: row.Prefix, Digest: row.Digest,
		CreatedAt: row.CredentialCreatedAt, ExpiresAt: timePointer(row.ExpiresAt), LastUsedAt: timePointer(row.LastUsedAt), RevokedAt: timePointer(row.RevokedAt),
	}
	return configuration, credential, nil
}

func (s *Store) SaveSCIMCredential(ctx context.Context, credential credbound.SCIMCredential, commit credbound.Commit) error {
	return s.mutate(ctx, commit, func(q *db.Queries) error { return insertSCIMCredential(ctx, q, credential) })
}

func (s *Store) RevokeSCIMCredential(ctx context.Context, configurationID, id string, revokedAt time.Time, commit credbound.Commit) error {
	return s.mutate(ctx, commit, func(q *db.Queries) error {
		count, err := q.RevokeSCIMCredential(ctx, db.RevokeSCIMCredentialParams{
			ConfigurationID: configurationID, ID: id, RevokedAt: nullableTime(&revokedAt),
		})
		return affected(count, err)
	})
}

func (s *Store) TouchSCIMCredential(ctx context.Context, id string, usedAt time.Time, commit credbound.Commit) error {
	return s.mutate(ctx, commit, func(q *db.Queries) error {
		count, err := q.TouchSCIMCredential(ctx, db.TouchSCIMCredentialParams{ID: id, LastUsedAt: nullableTime(&usedAt)})
		return affected(count, err)
	})
}

func (s *Store) DisableSCIMConfiguration(ctx context.Context, id string, disabledAt time.Time, commit credbound.Commit) error {
	return s.mutate(ctx, commit, func(q *db.Queries) error {
		count, err := q.DisableSCIMConfiguration(ctx, db.DisableSCIMConfigurationParams{ID: id, UpdatedAt: disabledAt})
		if err := affected(count, err); err != nil {
			return err
		}
		return mapError(q.RevokeSCIMCredentials(ctx, db.RevokeSCIMCredentialsParams{ConfigurationID: id, RevokedAt: nullableTime(&disabledAt)}))
	})
}

func (s *Store) CreateSCIMUser(ctx context.Context, user credbound.User, email credbound.EmailAddress, membership credbound.Membership, link credbound.SCIMUser, commit credbound.Commit) error {
	return s.mutate(ctx, commit, func(q *db.Queries) error {
		if err := insertUser(ctx, q, user); err != nil {
			return err
		}
		if err := insertEmail(ctx, q, email, credbound.EmailVerificationCredential{}); err != nil {
			return err
		}
		if err := upsertMembership(ctx, q, membership); err != nil {
			return err
		}
		return insertSCIMUser(ctx, q, link)
	})
}

func (s *Store) AdoptSCIMUser(ctx context.Context, membership credbound.Membership, link credbound.SCIMUser, commit credbound.Commit) error {
	return s.mutate(ctx, commit, func(q *db.Queries) error {
		if err := upsertMembership(ctx, q, membership); err != nil {
			return err
		}
		return insertSCIMUser(ctx, q, link)
	})
}

func (s *Store) SCIMUser(ctx context.Context, configurationID, id string) (credbound.SCIMUser, error) {
	row, err := s.queries.GetSCIMUser(ctx, db.GetSCIMUserParams{ConfigurationID: configurationID, ID: id})
	if err != nil {
		return credbound.SCIMUser{}, mapError(err)
	}
	return scimUserFromRow(row)
}

func (s *Store) SCIMUserByExternalID(ctx context.Context, configurationID, externalID string) (credbound.SCIMUser, error) {
	row, err := s.queries.GetSCIMUserByExternalID(ctx, db.GetSCIMUserByExternalIDParams{ConfigurationID: configurationID, ExternalID: nullableString(externalID)})
	if err != nil {
		return credbound.SCIMUser{}, mapError(err)
	}
	return scimUserFromRow(row)
}

func (s *Store) SCIMUserByUserName(ctx context.Context, configurationID, userName string) (credbound.SCIMUser, error) {
	row, err := s.queries.GetSCIMUserByUserName(ctx, db.GetSCIMUserByUserNameParams{ConfigurationID: configurationID, NormalizedUserName: strings.ToLower(strings.TrimSpace(userName))})
	if err != nil {
		return credbound.SCIMUser{}, mapError(err)
	}
	return scimUserFromRow(row)
}

func (s *Store) UpdateSCIMUser(ctx context.Context, link credbound.SCIMUser, membership credbound.Membership, revokeWorkspacePATs bool, commit credbound.Commit) error {
	return s.mutate(ctx, commit, func(q *db.Queries) error {
		emails, profile, err := encodeSCIMUserJSON(link)
		if err != nil {
			return err
		}
		count, err := q.UpdateSCIMUser(ctx, db.UpdateSCIMUserParams{
			ConfigurationID: link.ConfigurationID, ID: link.ID, ExternalID: nullableString(link.ExternalID),
			NormalizedUserName: link.UserName, DisplayName: link.DisplayName, EmailsJson: emails, ProfileJson: profile, Active: sqlBool(link.Active),
			UpdatedAt: link.UpdatedAt, DeprovisionedAt: nullableTime(link.DeprovisionedAt),
		})
		if err := affected(count, err); err != nil {
			return err
		}
		if err := upsertMembership(ctx, q, membership); err != nil {
			return err
		}
		if revokeWorkspacePATs {
			return mapError(q.RevokeWorkspacePATs(ctx, db.RevokeWorkspacePATsParams{
				UserID: link.UserID, WorkspaceID: nullableString(membership.WorkspaceID), RevokedAt: nullableTime(&link.UpdatedAt),
			}))
		}
		return nil
	})
}

func (s *Store) SCIMUsers(ctx context.Context, configurationID string, filter credbound.SCIMFilter, page credbound.PageRequest) iter.Seq2[credbound.PageEvent[credbound.SCIMUser], error] {
	return func(yield func(credbound.PageEvent[credbound.SCIMUser], error) bool) {
		streamCtx, cancel := context.WithTimeout(ctx, s.streamTimeout)
		defer cancel()
		cursor, err := decodeCursor(page.Cursor)
		if err != nil {
			yield(credbound.PageEvent[credbound.SCIMUser]{}, err)
			return
		}
		query, args, err := postgresSCIMUserListQuery(configurationID, filter, cursor, page.Limit+1)
		if err != nil {
			yield(credbound.PageEvent[credbound.SCIMUser]{}, err)
			return
		}
		rows, err := s.rows.Query(streamCtx, query, args...)
		if err != nil {
			yield(credbound.PageEvent[credbound.SCIMUser]{}, mapError(err))
			return
		}
		defer rows.Close()
		var last credbound.SCIMUser
		count := 0
		for rows.Next() {
			value, err := scanSCIMUser(rows)
			if err != nil {
				yield(credbound.PageEvent[credbound.SCIMUser]{}, err)
				return
			}
			if count == page.Limit {
				yield(credbound.EndEvent[credbound.SCIMUser](credbound.PageEnd{HasMore: true, NextCursor: encodeCursor(last.CreatedAt, last.ID)}), nil)
				return
			}
			last, count = value, count+1
			if !yield(credbound.ItemEvent(value), nil) {
				return
			}
		}
		if err := rows.Err(); err != nil {
			yield(credbound.PageEvent[credbound.SCIMUser]{}, err)
			return
		}
		yield(credbound.EndEvent[credbound.SCIMUser](credbound.PageEnd{}), nil)
	}
}

func (s *Store) UpsertSCIMGroup(ctx context.Context, group credbound.SCIMGroup, memberships []credbound.Membership, commit credbound.Commit) error {
	return s.mutate(ctx, commit, func(q *db.Queries) error {
		members, err := json.Marshal(group.MemberIDs)
		if err != nil {
			return err
		}
		if err := q.UpsertSCIMGroup(ctx, db.UpsertSCIMGroupParams{
			ID: group.ID, ConfigurationID: group.ConfigurationID, ExternalID: nullableString(group.ExternalID), DisplayName: group.DisplayName,
			MemberIdsJson: members, CreatedAt: group.CreatedAt, UpdatedAt: group.UpdatedAt, DeletedAt: nullableTime(group.DeletedAt),
		}); err != nil {
			return mapError(err)
		}
		for _, membership := range memberships {
			if err := upsertMembership(ctx, q, membership); err != nil {
				return err
			}
		}
		return nil
	})
}

func (s *Store) SCIMGroup(ctx context.Context, configurationID, id string) (credbound.SCIMGroup, error) {
	row, err := s.queries.GetSCIMGroup(ctx, db.GetSCIMGroupParams{ConfigurationID: configurationID, ID: id})
	if err != nil {
		return credbound.SCIMGroup{}, mapError(err)
	}
	return scimGroupFromRow(row)
}

func (s *Store) SCIMGroupByExternalID(ctx context.Context, configurationID, externalID string) (credbound.SCIMGroup, error) {
	row, err := s.queries.GetSCIMGroupByExternalID(ctx, db.GetSCIMGroupByExternalIDParams{ConfigurationID: configurationID, ExternalID: nullableString(externalID)})
	if err != nil {
		return credbound.SCIMGroup{}, mapError(err)
	}
	return scimGroupFromRow(row)
}

func (s *Store) DeleteSCIMGroup(ctx context.Context, group credbound.SCIMGroup, memberships []credbound.Membership, commit credbound.Commit) error {
	return s.mutate(ctx, commit, func(q *db.Queries) error {
		count, err := q.DeleteSCIMGroup(ctx, db.DeleteSCIMGroupParams{
			ConfigurationID: group.ConfigurationID, ID: group.ID, DeletedAt: nullableTime(group.DeletedAt), UpdatedAt: group.UpdatedAt,
		})
		if err := affected(count, err); err != nil {
			return err
		}
		for _, membership := range memberships {
			if err := upsertMembership(ctx, q, membership); err != nil {
				return err
			}
		}
		return nil
	})
}

func (s *Store) SCIMGroups(ctx context.Context, configurationID string, filter credbound.SCIMFilter, page credbound.PageRequest) iter.Seq2[credbound.PageEvent[credbound.SCIMGroup], error] {
	return func(yield func(credbound.PageEvent[credbound.SCIMGroup], error) bool) {
		streamCtx, cancel := context.WithTimeout(ctx, s.streamTimeout)
		defer cancel()
		cursor, err := decodeCursor(page.Cursor)
		if err != nil {
			yield(credbound.PageEvent[credbound.SCIMGroup]{}, err)
			return
		}
		query, args, err := postgresSCIMGroupListQuery(configurationID, filter, cursor, page.Limit+1)
		if err != nil {
			yield(credbound.PageEvent[credbound.SCIMGroup]{}, err)
			return
		}
		rows, err := s.rows.Query(streamCtx, query, args...)
		if err != nil {
			yield(credbound.PageEvent[credbound.SCIMGroup]{}, mapError(err))
			return
		}
		defer rows.Close()
		var last credbound.SCIMGroup
		count := 0
		for rows.Next() {
			value, err := scanSCIMGroup(rows)
			if err != nil {
				yield(credbound.PageEvent[credbound.SCIMGroup]{}, err)
				return
			}
			if count == page.Limit {
				yield(credbound.EndEvent[credbound.SCIMGroup](credbound.PageEnd{HasMore: true, NextCursor: encodeCursor(last.CreatedAt, last.ID)}), nil)
				return
			}
			last, count = value, count+1
			if !yield(credbound.ItemEvent(value), nil) {
				return
			}
		}
		if err := rows.Err(); err != nil {
			yield(credbound.PageEvent[credbound.SCIMGroup]{}, err)
			return
		}
		yield(credbound.EndEvent[credbound.SCIMGroup](credbound.PageEnd{}), nil)
	}
}

func insertSCIMConfiguration(ctx context.Context, q *db.Queries, value credbound.SCIMConfiguration) error {
	mappings, err := json.Marshal(value.GroupRoleMappings)
	if err != nil {
		return err
	}
	return mapError(q.InsertSCIMConfiguration(ctx, db.InsertSCIMConfigurationParams{
		ID: value.ID, WorkspaceID: value.WorkspaceID, Enabled: sqlBool(value.Enabled), DefaultRole: string(value.DefaultRole),
		TrustDirectoryEmails: sqlBool(value.TrustDirectoryEmails), GroupRoleMappingsJson: mappings, CreatedAt: value.CreatedAt, UpdatedAt: value.UpdatedAt,
	}))
}

func insertSCIMCredential(ctx context.Context, q *db.Queries, value credbound.SCIMCredential) error {
	return mapError(q.InsertSCIMCredential(ctx, db.InsertSCIMCredentialParams{
		ID: value.ID, ConfigurationID: value.ConfigurationID, Prefix: value.Prefix, Digest: value.Digest, CreatedAt: value.CreatedAt,
		ExpiresAt: nullableTime(value.ExpiresAt), LastUsedAt: nullableTime(value.LastUsedAt), RevokedAt: nullableTime(value.RevokedAt),
	}))
}

func insertSCIMUser(ctx context.Context, q *db.Queries, value credbound.SCIMUser) error {
	emails, profile, err := encodeSCIMUserJSON(value)
	if err != nil {
		return err
	}
	return mapError(q.InsertSCIMUser(ctx, db.InsertSCIMUserParams{
		ID: value.ID, ConfigurationID: value.ConfigurationID, UserID: value.UserID, ExternalID: nullableString(value.ExternalID),
		NormalizedUserName: value.UserName, DisplayName: value.DisplayName, EmailsJson: emails, ProfileJson: profile, Active: sqlBool(value.Active),
		CreatedAt: value.CreatedAt, UpdatedAt: value.UpdatedAt, DeprovisionedAt: nullableTime(value.DeprovisionedAt),
	}))
}

func scimConfigurationFromRow(row db.CredboundScimConfiguration) (credbound.SCIMConfiguration, error) {
	return decodeSCIMConfiguration(row.ID, row.WorkspaceID, row.Enabled, row.DefaultRole, row.TrustDirectoryEmails, []byte(row.GroupRoleMappingsJson), row.CreatedAt, row.UpdatedAt)
}

func scimConfigurationFromCredentialRow(row db.GetSCIMConfigurationByCredentialPrefixRow) (credbound.SCIMConfiguration, error) {
	return decodeSCIMConfiguration(row.ID, row.WorkspaceID, row.Enabled, row.DefaultRole, row.TrustDirectoryEmails, []byte(row.GroupRoleMappingsJson), row.CreatedAt, row.UpdatedAt)
}

func decodeSCIMConfiguration(id, workspaceID string, enabled bool, defaultRole string, trust bool, mappingsJSON []byte, createdAt, updatedAt time.Time) (credbound.SCIMConfiguration, error) {
	var mappings []credbound.SCIMGroupRoleMapping
	if err := json.Unmarshal(mappingsJSON, &mappings); err != nil {
		return credbound.SCIMConfiguration{}, err
	}
	return credbound.SCIMConfiguration{
		ID: id, WorkspaceID: workspaceID, Enabled: enabled, DefaultRole: credbound.Role(defaultRole), TrustDirectoryEmails: trust,
		GroupRoleMappings: mappings, CreatedAt: createdAt, UpdatedAt: updatedAt,
	}, nil
}

func scimUserFromRow(row db.CredboundScimUser) (credbound.SCIMUser, error) {
	return decodeSCIMUser(row.ID, row.ConfigurationID, row.UserID, row.ExternalID.String, row.NormalizedUserName, row.DisplayName, []byte(row.EmailsJson), []byte(row.ProfileJson), row.Active, row.CreatedAt, row.UpdatedAt, row.DeprovisionedAt)
}

type scimUserProfile struct {
	Schemas    []string                   `json:"schemas,omitempty"`
	Attributes map[string]json.RawMessage `json:"attributes,omitempty"`
}

func encodeSCIMUserJSON(value credbound.SCIMUser) ([]byte, []byte, error) {
	emails, err := json.Marshal(value.Emails)
	if err != nil {
		return nil, nil, err
	}
	profile, err := json.Marshal(scimUserProfile{Schemas: value.Schemas, Attributes: value.Attributes})
	return emails, profile, err
}

func decodeSCIMUser(id, configurationID, userID, externalID, userName, displayName string, emailsJSON, profileJSON []byte, active bool, createdAt, updatedAt time.Time, deprovisioned sql.NullTime) (credbound.SCIMUser, error) {
	var emails []credbound.SCIMEmail
	if err := json.Unmarshal(emailsJSON, &emails); err != nil {
		return credbound.SCIMUser{}, err
	}
	var profile scimUserProfile
	if err := json.Unmarshal(profileJSON, &profile); err != nil {
		return credbound.SCIMUser{}, err
	}
	return credbound.SCIMUser{
		ID: id, ConfigurationID: configurationID, UserID: userID, ExternalID: externalID, UserName: userName, DisplayName: displayName,
		Schemas: profile.Schemas, Emails: emails, Attributes: profile.Attributes, Active: active, CreatedAt: createdAt, UpdatedAt: updatedAt, DeprovisionedAt: timePointer(deprovisioned),
	}, nil
}

func scimGroupFromRow(row db.CredboundScimGroup) (credbound.SCIMGroup, error) {
	return decodeSCIMGroup(row.ID, row.ConfigurationID, row.ExternalID.String, row.DisplayName, []byte(row.MemberIdsJson), row.CreatedAt, row.UpdatedAt, row.DeletedAt)
}

func decodeSCIMGroup(id, configurationID, externalID, displayName string, membersJSON []byte, createdAt, updatedAt time.Time, deleted sql.NullTime) (credbound.SCIMGroup, error) {
	var members []string
	if err := json.Unmarshal(membersJSON, &members); err != nil {
		return credbound.SCIMGroup{}, err
	}
	return credbound.SCIMGroup{
		ID: id, ConfigurationID: configurationID, ExternalID: externalID, DisplayName: displayName, MemberIDs: members,
		CreatedAt: createdAt, UpdatedAt: updatedAt, DeletedAt: timePointer(deleted),
	}, nil
}

func scanSCIMUser(row scanner) (credbound.SCIMUser, error) {
	var id, configurationID, userID, userName, displayName string
	var emails, profile []byte
	var external sql.NullString
	var active bool
	var createdAt, updatedAt time.Time
	var deprovisioned sql.NullTime
	if err := row.Scan(&id, &configurationID, &userID, &external, &userName, &displayName, &emails, &profile, &active, &createdAt, &updatedAt, &deprovisioned); err != nil {
		return credbound.SCIMUser{}, err
	}
	return decodeSCIMUser(id, configurationID, userID, external.String, userName, displayName, []byte(emails), []byte(profile), active, createdAt, updatedAt, deprovisioned)
}

func scanSCIMGroup(row scanner) (credbound.SCIMGroup, error) {
	var id, configurationID, displayName string
	var members []byte
	var external sql.NullString
	var createdAt, updatedAt time.Time
	var deleted sql.NullTime
	if err := row.Scan(&id, &configurationID, &external, &displayName, &members, &createdAt, &updatedAt, &deleted); err != nil {
		return credbound.SCIMGroup{}, err
	}
	return decodeSCIMGroup(id, configurationID, external.String, displayName, []byte(members), createdAt, updatedAt, deleted)
}

func postgresSCIMUserListQuery(configurationID string, filter credbound.SCIMFilter, cursor cursor, limit int) (string, []any, error) {
	query := `SELECT id, configuration_id, user_id, external_id, normalized_user_name, display_name, emails_json, profile_json, active, created_at, updated_at, deprovisioned_at
FROM credbound.scim_users WHERE configuration_id = $1 AND deprovisioned_at IS NULL`
	args := []any{configurationID}
	next := 2
	add := func(fragment string, value any) {
		query += fmt.Sprintf(fragment, next)
		args = append(args, value)
		next++
	}
	switch filter.Attribute {
	case "":
	case "id":
		add(" AND id::text = $%d", filter.Value)
	case "externalId":
		add(" AND external_id = $%d", filter.Value)
	case "userName":
		add(" AND normalized_user_name = $%d", strings.ToLower(strings.TrimSpace(filter.Value)))
	case "emails.value":
		add(" AND EXISTS (SELECT 1 FROM jsonb_array_elements(emails_json) e WHERE e->>'value' = $%d)", strings.ToLower(strings.TrimSpace(filter.Value)))
	case "active":
		value := false
		if strings.EqualFold(filter.Value, "true") {
			value = true
		} else if !strings.EqualFold(filter.Value, "false") {
			return "", nil, fmt.Errorf("%w: invalid active filter", credbound.ErrInvalidInput)
		}
		add(" AND active = $%d", value)
	default:
		return "", nil, fmt.Errorf("%w: unsupported SCIM user filter", credbound.ErrInvalidInput)
	}
	query += fmt.Sprintf(" AND (NOT $%d OR created_at < $%d OR (created_at = $%d AND id < $%d)) ORDER BY created_at DESC, id DESC LIMIT $%d", next, next+1, next+2, next+3, next+4)
	args = append(args, cursor.ID != "", cursor.Time, cursor.Time, nullableUUID(cursor.ID), limit)
	return query, args, nil
}

func postgresSCIMGroupListQuery(configurationID string, filter credbound.SCIMFilter, cursor cursor, limit int) (string, []any, error) {
	query := `SELECT id, configuration_id, external_id, display_name, member_ids_json, created_at, updated_at, deleted_at
FROM credbound.scim_groups WHERE configuration_id = $1 AND deleted_at IS NULL`
	args := []any{configurationID}
	next := 2
	switch filter.Attribute {
	case "":
	case "id":
		query += fmt.Sprintf(" AND id::text = $%d", next)
		args, next = append(args, filter.Value), next+1
	case "externalId":
		query += fmt.Sprintf(" AND external_id = $%d", next)
		args, next = append(args, filter.Value), next+1
	case "displayName":
		query += fmt.Sprintf(" AND display_name = $%d", next)
		args, next = append(args, filter.Value), next+1
	default:
		return "", nil, fmt.Errorf("%w: unsupported SCIM group filter", credbound.ErrInvalidInput)
	}
	query += fmt.Sprintf(" AND (NOT $%d OR created_at < $%d OR (created_at = $%d AND id < $%d)) ORDER BY created_at DESC, id DESC LIMIT $%d", next, next+1, next+2, next+3, next+4)
	args = append(args, cursor.ID != "", cursor.Time, cursor.Time, nullableUUID(cursor.ID), limit)
	return query, args, nil
}

func sqlBool(value bool) bool { return value }

var _ credbound.SCIMStore = (*Store)(nil)
