// Command genpostgresstore derives the PostgreSQL store from the SQLite one.
//
// The two stores share their logic verbatim: the sqlc layers are generated
// with matching Go types (see the overrides in sqlc.yaml), the hand-written
// statements are phrased in the portable form both engines accept, and every
// read-then-write invariant is guarded by a Lock* query that is a plain read
// on SQLite and SELECT … FOR UPDATE on PostgreSQL. What genuinely differs —
// construction, error classification, statement translation, the concurrency
// strategy and the two SCIM filter fragments — is written by hand in each
// package's dialect.go and is never touched here.
//
// So this command only re-points a copy at the other package: the package
// clause and the sqlc import. If a future change needs more than that, add it
// to dialect.go rather than to this file — a patch list is how this generator
// grew to 117 replacements once already.
package main

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
)

const (
	sourceDir = "sqlstore/sqlite"
	targetDir = "sqlstore/postgresql"
	header    = "// Code generated by internal/cmd/genpostgresstore; DO NOT EDIT.\n\n"
)

// handWritten names the files each package owns outright. They are the whole
// of the dialect surface, so everything else must be dialect-neutral.
var handWritten = map[string]bool{"dialect.go": true, "doc.go": true}

func main() {
	entries, err := os.ReadDir(sourceDir)
	if err != nil {
		panic(err)
	}
	for _, entry := range entries {
		name := entry.Name()
		if entry.IsDir() || !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") || handWritten[name] {
			continue
		}
		if err := derive(name); err != nil {
			panic(err)
		}
		fmt.Println(filepath.Join(targetDir, name))
	}
}

func derive(name string) error {
	raw, err := os.ReadFile(filepath.Join(sourceDir, name))
	if err != nil {
		return err
	}
	code := string(raw)
	code, err = mustReplace(code, "package sqlite", "package postgresql")
	if err != nil {
		return fmt.Errorf("%s: %w", name, err)
	}
	if strings.Contains(code, "internal/sqlc/sqlite") {
		code, err = mustReplace(code,
			`db "github.com/deepteams/credbound/internal/sqlc/sqlite"`,
			`db "github.com/deepteams/credbound/internal/sqlc/postgresql"`)
		if err != nil {
			return fmt.Errorf("%s: %w", name, err)
		}
	}
	formatted, err := format.Source([]byte(header + code))
	if err != nil {
		return fmt.Errorf("format %s: %w", name, err)
	}
	if err := os.MkdirAll(targetDir, 0o755); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(targetDir, name), formatted, 0o644)
}

// mustReplace substitutes the single occurrence of old and fails loudly when
// the source no longer contains it, so a drifted SQLite store can never
// silently ship SQLite artifacts under the postgresql package name.
func mustReplace(code, old, new string) (string, error) {
	switch strings.Count(code, old) {
	case 1:
		return strings.Replace(code, old, new, 1), nil
	case 0:
		return "", fmt.Errorf("replacement source not found: %q", old)
	default:
		return "", fmt.Errorf("replacement source is ambiguous: %q", old)
	}
}
