// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgresql

import (
	"database/sql"
	"encoding/json"
	"time"
)

type CredboundAuditChain struct {
	Singleton int32  `json:"singleton"`
	Sequence  int64  `json:"sequence"`
	HeadHash  []byte `json:"head_hash"`
}

type CredboundAuditEvent struct {
	ID           string         `json:"id"`
	OccurredAt   time.Time      `json:"occurred_at"`
	ActorKind    string         `json:"actor_kind"`
	ActorID      sql.NullString `json:"actor_id"`
	Action       string         `json:"action"`
	ResourceType string         `json:"resource_type"`
	ResourceID   string         `json:"resource_id"`
	WorkspaceID  sql.NullString `json:"workspace_id"`
	Outcome      string         `json:"outcome"`
	Reason       string         `json:"reason"`
	IpAddress    string         `json:"ip_address"`
	UserAgent    string         `json:"user_agent"`
	Sequence     sql.NullInt64  `json:"sequence"`
	PreviousHash []byte         `json:"previous_hash"`
	Hash         []byte         `json:"hash"`
}

type CredboundConsumedCeremony struct {
	ID        string    `json:"id"`
	ExpiresAt time.Time `json:"expires_at"`
}

type CredboundEmailAuthentication struct {
	ID        string       `json:"id"`
	UserID    string       `json:"user_id"`
	EmailID   string       `json:"email_id"`
	Digest    []byte       `json:"digest"`
	CreatedAt time.Time    `json:"created_at"`
	ExpiresAt time.Time    `json:"expires_at"`
	UsedAt    sql.NullTime `json:"used_at"`
}

type CredboundEmailIssuance struct {
	Address      string    `json:"address"`
	Purpose      string    `json:"purpose"`
	LastIssuedAt time.Time `json:"last_issued_at"`
}

type CredboundInstance struct {
	Singleton     bool      `json:"singleton"`
	InitializedAt time.Time `json:"initialized_at"`
}

type CredboundInstanceAdministrator struct {
	UserID    string    `json:"user_id"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type CredboundLoginThrottle struct {
	UserID         string       `json:"user_id"`
	FailedAttempts int64        `json:"failed_attempts"`
	LockedUntil    sql.NullTime `json:"locked_until"`
	UpdatedAt      time.Time    `json:"updated_at"`
}

type CredboundMembership struct {
	WorkspaceID        string    `json:"workspace_id"`
	UserID             string    `json:"user_id"`
	Role               string    `json:"role"`
	Status             string    `json:"status"`
	ProvisioningSource string    `json:"provisioning_source"`
	CreatedAt          time.Time `json:"created_at"`
	UpdatedAt          time.Time `json:"updated_at"`
}

type CredboundOauthAccessToken struct {
	ID       string          `json:"id"`
	Prefix   string          `json:"prefix"`
	GrantID  string          `json:"grant_id"`
	DataJson json.RawMessage `json:"data_json"`
}

type CredboundOauthAuthorizationCode struct {
	ID        string          `json:"id"`
	Prefix    string          `json:"prefix"`
	GrantID   string          `json:"grant_id"`
	UsedAt    sql.NullTime    `json:"used_at"`
	ExpiresAt time.Time       `json:"expires_at"`
	DataJson  json.RawMessage `json:"data_json"`
}

type CredboundOauthClient struct {
	ID        string          `json:"id"`
	IssuerID  string          `json:"issuer_id"`
	ClientID  string          `json:"client_id"`
	CreatedAt time.Time       `json:"created_at"`
	DataJson  json.RawMessage `json:"data_json"`
}

type CredboundOauthClientAccessToken struct {
	ID             string          `json:"id"`
	Prefix         string          `json:"prefix"`
	ClientRecordID string          `json:"client_record_id"`
	DataJson       json.RawMessage `json:"data_json"`
}

type CredboundOauthGrant struct {
	ID             string          `json:"id"`
	ClientRecordID string          `json:"client_record_id"`
	ResourceID     string          `json:"resource_id"`
	UserID         string          `json:"user_id"`
	WorkspaceID    string          `json:"workspace_id"`
	CreatedAt      time.Time       `json:"created_at"`
	DataJson       json.RawMessage `json:"data_json"`
}

type CredboundOauthInitialAccessToken struct {
	ID                string          `json:"id"`
	IssuerID          string          `json:"issuer_id"`
	Prefix            string          `json:"prefix"`
	RegistrationCount int32           `json:"registration_count"`
	MaxRegistrations  int32           `json:"max_registrations"`
	ExpiresAt         time.Time       `json:"expires_at"`
	RevokedAt         sql.NullTime    `json:"revoked_at"`
	DataJson          json.RawMessage `json:"data_json"`
}

type CredboundOauthIssuer struct {
	ID        string          `json:"id"`
	Issuer    string          `json:"issuer"`
	CreatedAt time.Time       `json:"created_at"`
	DataJson  json.RawMessage `json:"data_json"`
}

type CredboundOauthRefreshToken struct {
	ID        string          `json:"id"`
	FamilyID  string          `json:"family_id"`
	Prefix    string          `json:"prefix"`
	GrantID   string          `json:"grant_id"`
	UsedAt    sql.NullTime    `json:"used_at"`
	RevokedAt sql.NullTime    `json:"revoked_at"`
	ExpiresAt time.Time       `json:"expires_at"`
	DataJson  json.RawMessage `json:"data_json"`
}

type CredboundOauthResource struct {
	ID          string          `json:"id"`
	IssuerID    string          `json:"issuer_id"`
	WorkspaceID string          `json:"workspace_id"`
	Resource    string          `json:"resource"`
	CreatedAt   time.Time       `json:"created_at"`
	DataJson    json.RawMessage `json:"data_json"`
}

type CredboundPasskey struct {
	ID             string       `json:"id"`
	UserID         string       `json:"user_id"`
	Name           string       `json:"name"`
	CredentialID   []byte       `json:"credential_id"`
	CredentialJson []byte       `json:"credential_json"`
	CreatedAt      time.Time    `json:"created_at"`
	LastUsedAt     sql.NullTime `json:"last_used_at"`
}

type CredboundPasswordCredential struct {
	UserID    string    `json:"user_id"`
	Hash      string    `json:"hash"`
	UpdatedAt time.Time `json:"updated_at"`
}

type CredboundPasswordReset struct {
	ID        string       `json:"id"`
	UserID    string       `json:"user_id"`
	Digest    []byte       `json:"digest"`
	CreatedAt time.Time    `json:"created_at"`
	ExpiresAt time.Time    `json:"expires_at"`
	UsedAt    sql.NullTime `json:"used_at"`
}

type CredboundPersonalAccessToken struct {
	ID          string          `json:"id"`
	UserID      string          `json:"user_id"`
	Name        string          `json:"name"`
	Prefix      string          `json:"prefix"`
	Digest      []byte          `json:"digest"`
	WorkspaceID sql.NullString  `json:"workspace_id"`
	ScopesJson  json.RawMessage `json:"scopes_json"`
	CreatedAt   time.Time       `json:"created_at"`
	ExpiresAt   sql.NullTime    `json:"expires_at"`
	LastUsedAt  sql.NullTime    `json:"last_used_at"`
	RevokedAt   sql.NullTime    `json:"revoked_at"`
}

type CredboundRecoveryCode struct {
	UserID string       `json:"user_id"`
	Digest []byte       `json:"digest"`
	UsedAt sql.NullTime `json:"used_at"`
}

type CredboundScimConfiguration struct {
	ID                    string          `json:"id"`
	WorkspaceID           string          `json:"workspace_id"`
	Enabled               bool            `json:"enabled"`
	DefaultRole           string          `json:"default_role"`
	TrustDirectoryEmails  bool            `json:"trust_directory_emails"`
	GroupRoleMappingsJson json.RawMessage `json:"group_role_mappings_json"`
	CreatedAt             time.Time       `json:"created_at"`
	UpdatedAt             time.Time       `json:"updated_at"`
}

type CredboundScimCredential struct {
	ID              string       `json:"id"`
	ConfigurationID string       `json:"configuration_id"`
	Prefix          string       `json:"prefix"`
	Digest          []byte       `json:"digest"`
	CreatedAt       time.Time    `json:"created_at"`
	ExpiresAt       sql.NullTime `json:"expires_at"`
	LastUsedAt      sql.NullTime `json:"last_used_at"`
	RevokedAt       sql.NullTime `json:"revoked_at"`
}

type CredboundScimGroup struct {
	ID              string          `json:"id"`
	ConfigurationID string          `json:"configuration_id"`
	ExternalID      sql.NullString  `json:"external_id"`
	DisplayName     string          `json:"display_name"`
	MemberIdsJson   json.RawMessage `json:"member_ids_json"`
	CreatedAt       time.Time       `json:"created_at"`
	UpdatedAt       time.Time       `json:"updated_at"`
	DeletedAt       sql.NullTime    `json:"deleted_at"`
}

type CredboundScimUser struct {
	ID                 string          `json:"id"`
	ConfigurationID    string          `json:"configuration_id"`
	UserID             string          `json:"user_id"`
	ExternalID         sql.NullString  `json:"external_id"`
	NormalizedUserName string          `json:"normalized_user_name"`
	DisplayName        string          `json:"display_name"`
	EmailsJson         json.RawMessage `json:"emails_json"`
	ProfileJson        json.RawMessage `json:"profile_json"`
	Active             bool            `json:"active"`
	CreatedAt          time.Time       `json:"created_at"`
	UpdatedAt          time.Time       `json:"updated_at"`
	DeprovisionedAt    sql.NullTime    `json:"deprovisioned_at"`
}

type CredboundSession struct {
	ID                   string       `json:"id"`
	UserID               string       `json:"user_id"`
	Method               string       `json:"method"`
	Level                int16        `json:"level"`
	AuthenticatedAt      time.Time    `json:"authenticated_at"`
	SecondFactorRequired bool         `json:"second_factor_required"`
	UserAgent            string       `json:"user_agent"`
	IpAddress            string       `json:"ip_address"`
	Digest               []byte       `json:"digest"`
	CreatedAt            time.Time    `json:"created_at"`
	LastSeenAt           time.Time    `json:"last_seen_at"`
	ExpiresAt            time.Time    `json:"expires_at"`
	RevokedAt            sql.NullTime `json:"revoked_at"`
}

type CredboundSsoIdentity struct {
	ID                      string       `json:"id"`
	UserID                  string       `json:"user_id"`
	ProviderConfigurationID string       `json:"provider_configuration_id"`
	ProviderKind            string       `json:"provider_kind"`
	Issuer                  string       `json:"issuer"`
	Subject                 string       `json:"subject"`
	Email                   string       `json:"email"`
	CreatedAt               time.Time    `json:"created_at"`
	LastUsedAt              sql.NullTime `json:"last_used_at"`
}

type CredboundTotpFactor struct {
	UserID          string    `json:"user_id"`
	EncryptedSecret []byte    `json:"encrypted_secret"`
	Active          bool      `json:"active"`
	LastUsedStep    int64     `json:"last_used_step"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

type CredboundUser struct {
	ID          string       `json:"id"`
	DisplayName string       `json:"display_name"`
	Disabled    bool         `json:"disabled"`
	LastSeenAt  sql.NullTime `json:"last_seen_at"`
	CreatedAt   time.Time    `json:"created_at"`
	UpdatedAt   time.Time    `json:"updated_at"`
}

type CredboundUserEmail struct {
	ID                    string       `json:"id"`
	UserID                string       `json:"user_id"`
	Address               string       `json:"address"`
	IsPrimary             bool         `json:"is_primary"`
	VerifiedAt            sql.NullTime `json:"verified_at"`
	VerificationDigest    []byte       `json:"verification_digest"`
	VerificationExpiresAt sql.NullTime `json:"verification_expires_at"`
	CreatedAt             time.Time    `json:"created_at"`
	UpdatedAt             time.Time    `json:"updated_at"`
}

type CredboundWorkspace struct {
	ID         string       `json:"id"`
	Name       string       `json:"name"`
	CreatedAt  time.Time    `json:"created_at"`
	UpdatedAt  time.Time    `json:"updated_at"`
	DisabledAt sql.NullTime `json:"disabled_at"`
	RequireMfa bool         `json:"require_mfa"`
}

type CredboundWorkspaceDomain struct {
	ID                         string       `json:"id"`
	WorkspaceID                string       `json:"workspace_id"`
	Domain                     string       `json:"domain"`
	Challenge                  string       `json:"challenge"`
	ConfirmedAt                sql.NullTime `json:"confirmed_at"`
	AutoJoin                   bool         `json:"auto_join"`
	AutoJoinRole               string       `json:"auto_join_role"`
	SsoProviderConfigurationID string       `json:"sso_provider_configuration_id"`
	EnforceSso                 bool         `json:"enforce_sso"`
	CreatedAt                  time.Time    `json:"created_at"`
	UpdatedAt                  time.Time    `json:"updated_at"`
}

type CredboundWorkspaceInvitation struct {
	ID             string         `json:"id"`
	WorkspaceID    string         `json:"workspace_id"`
	Email          string         `json:"email"`
	Role           string         `json:"role"`
	InvitedBy      string         `json:"invited_by"`
	Digest         []byte         `json:"digest"`
	CreatedAt      time.Time      `json:"created_at"`
	ExpiresAt      time.Time      `json:"expires_at"`
	AcceptedAt     sql.NullTime   `json:"accepted_at"`
	AcceptedUserID sql.NullString `json:"accepted_user_id"`
	RevokedAt      sql.NullTime   `json:"revoked_at"`
}
